[tool.black]
line-length = 100

[tool.isort]
line_length = 100
indent = '    '
multi_line_output = 3
ensure_newline_before_comments = true
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true

[tool.poetry]
name = "securedrop-client"
version = "0.5.0"
description = "A Qt-based GUI for SecureDrop journalists"
authors = ["Freedom of the Press Foundation"]
license = "GNU Affero General Public License v3.0"

[tool.poetry.dependencies]
python = "^3.7"
alembic = "^1.0.2"
arrow = "^0.12.1"
certifi = "^2018.10.15"
chardet = "^3.0.4"
idna = "^2.7"
Mako = "^1.0.7"
MarkupSafe = "^1.1"
pathlib2 = "^2.3.2"
python-dateutil = "^2.7.5"
python-editor = "^1.0.3"
securedrop-sdk = "^0.3.0"
six = "^1.11.0"
SQLAlchemy = "^1.3.3"
urllib3 = "^1.25.10"
PyQt5 = "~5.11.3"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
atomicwrites = "^1.2.1"
attrs = "^19.3.0"
black = "^19.10b0"
Click = "^7.0"
coverage = "^4.5.1"
flake8 = "^.6.0"
flaky = "^3.6.1"
isort = "^4.3.21"
MarkupSafe = "^1.1"
mccabe = "^0.6.1"
more-itertools = "^4.3.0"
mypy = "^0.761"
mypy-extensions = "^0.4.3"
pillow = "^8.3.1"
pip = "^21.1"
pip-tools = "^5.5.0"
pluggy = "^0.13.0"
py = "^1.10.0"
PyAutoGUI = "^0.9.48"
pycodestyle = "^2.4.0"
pyflakes = "^2.0.0"
PyQt5 = "~5.11.3"
pytest = "^5.2.1"
pytest-cov = "^2.8.1"
pytest-mock = "^1.10.0"
pytest-qt = "^3.3.0"
pytest-random-order = "^1.0.4"
pytest-vcr = "^1.0.2"
pytest-xdist = "^1.30.0"
pyyaml = "^5.4.1"
semgrep = "^0.42.0"
sip = "^4.19.8"
typed-ast = "^1.4.1"
vcrpy = "^.0.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
