version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout

      - run: sudo apt-get install -y sqlite3

      - run:
          name: Install requirements and run tests
          command: |
            set -e
            virtualenv .venv
            source .venv/bin/activate
            pip install --require-hashes -r dev-requirements.txt
            export PYTHONPATH=$PYTHONPATH:.  # so alembic can get to Base metadata
            make check --keep-going

      - run:
          name: Check Python dependencies for known vulnerabilities
          command: |
            set -e
            source .venv/bin/activate
            make safety

      - run:
          name: Run static analysis on source code to find security issues
          command: |
            set -e
            source .venv/bin/activate
            make bandit
