"""add deleted column for pending operations

Revision ID: 476b3a500029
Revises: bd57477f19a2
Create Date: 2021-10-12 17:27:42.670143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476b3a500029'
down_revision = 'bd57477f19a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('deleted', sa.Boolean(name='deleted'), server_default=sa.text('0'), nullable=False))
    op.add_column('messages', sa.Column('deleted', sa.Boolean(name='deleted'), server_default=sa.text('0'), nullable=False))
    op.add_column('replies', sa.Column('deleted', sa.Boolean(name='deleted'), server_default=sa.text('0'), nullable=False))
    op.add_column('sources', sa.Column('deleted', sa.Boolean(name='deleted'), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'deleted')
    op.drop_column('replies', 'deleted')
    op.drop_column('messages', 'deleted')
    op.drop_column('files', 'deleted')
    # ### end Alembic commands ###
